#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Run from anywhere in the repo, not just infra/observability/ — write to the real repo-root
# .env, the same file infra/docker-compose.preprod.yaml reads via Compose's own interpolation.
if REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null); then
  ENV_FILE="$REPO_ROOT/.env"
else
  warn "not inside a git checkout — writing to ./.env in the current directory instead."
fi

TOTAL_STAGES=3

banner "Grafana Cloudflare Tunnel setup (ADR-0044)"

# ── Stage 1: orient — this is a second, independent tunnel ────────────────
stage "Before you start"
say "This wizard sets up a Cloudflare Tunnel dedicated to Grafana, on your own"
say "Cloudflare account. It is separate from the admin panel's production tunnel"
say "(a different token, CLOUDFLARE_TUNNEL_TOKEN, used only in"
say "infra/docker-compose.prod.yaml) — do not reuse that one here."
say ""
say "Grafana itself only binds 127.0.0.1 inside infra/docker-compose.preprod.yaml's"
say "observability profile; the grafana-cloudflared container is what's meant to"
say "make it reachable, once CLOUDFLARE_TUNNEL_TOKEN_GRAFANA is set below."
if command -v cloudflared >/dev/null 2>&1; then
  note "found a local cloudflared binary — you can use it for tunnel creation if you prefer"
  note "the dashboard flow below. Either path produces the same token."
else
  note "no local cloudflared binary found — that's fine, the dashboard flow below needs"
  note "nothing installed on this machine. The tunnel actually runs as the"
  note "grafana-cloudflared container, not on your host."
fi
pause "Ready?"

# ── Stage 2: create the tunnel and get its token ───────────────────────────
stage "Create the tunnel"
open_url "https://one.dash.cloudflare.com/"
step "Go to Networks → Tunnels (left sidebar, under Zero Trust)."
step "Click 'Create a tunnel', choose 'Cloudflared', and name it bitrate-grafana."
step "On the next screen, under 'Choose your environment', pick Docker."
step "You'll see a command containing a long --token value — copy just that token"
step "string (everything after --token), not the whole command."
note "Do not run that docker command yourself — infra/docker-compose.preprod.yaml's"
note "grafana-cloudflared service runs it for you, reading the token from .env."
ask_secret CLOUDFLARE_TUNNEL_TOKEN_GRAFANA "Paste the tunnel token:"
write_env CLOUDFLARE_TUNNEL_TOKEN_GRAFANA "$CLOUDFLARE_TUNNEL_TOKEN_GRAFANA"

# ── Stage 3: point the tunnel at Grafana ───────────────────────────────────
stage "Point the tunnel at Grafana"
say "Still on the tunnel's configuration page in the dashboard (or Networks →"
say "Tunnels → bitrate-grafana → Edit if you've moved on):"
step "Go to the 'Public Hostname' tab and click 'Add a public hostname'."
step "Pick a subdomain on a domain your Cloudflare account manages (e.g."
step "grafana.<yourdomain>) — this becomes the URL you'll open Grafana at."
step "Service type: HTTP. Service URL: grafana:3000"
note "grafana:3000 is the container's name and internal port on the bitrate-network"
note "Docker network — not a URL reachable from your own machine's browser. The"
note "grafana-cloudflared container resolves 'grafana' by that Docker DNS name only"
note "once both containers are on the same network, which task observability:up"
note "already sets up."
step "Save the hostname."
confirm "Public hostname added and saved?" || warn "you can add it later from the same dashboard page — nothing else depends on it to start the stack"

finish

say "Next: run 'task observability:up' from the repo root."
warn "grafana-cloudflared will keep exiting/restarting until CLOUDFLARE_TUNNEL_TOKEN_GRAFANA"
warn "is actually set — that's expected, not a bug, if you stopped before Stage 2."
