export const ROUTES = {
  landing: '/',
  auth: {
    login: '/login',
    registration: '/registration',
    verifyEmail: '/verify-email',
    forgotPassword: '/forgot-password',
  },
  dashboard: {
    home: '/dashboard',
    music: '/dashboard/music',
    tasks: '/dashboard/tasks',
    distribution: '/dashboard/distribution',
  },
  main: '/',
  legal: (slug: string) => `/legal/${slug}`,
  terms: '/legal/terms',
  artistAgreement: '/legal/artist-agreement',
  privacy: '/legal/privacy',
  community: '/legal/community',
  complaints: '/legal/complaints',
  copyright: '/legal/copyright',
  download: '#download',
  plans: '#plans',
  forStudents: '#for-students',
} as const
