#!/usr/bin/env node

/**
 * Bridges `.env` files into the Angular build.
 *
 * Angular has no `.env` support of its own — `@angular/build` never reads one, and `angular.json`
 * is static JSON that does not interpolate environment variables. The usual workaround is the
 * `define` option, but the `unit-test` builder does not accept `define` and inherits it from the
 * `build` target, so anything configured only for `build` leaves specs without a value. Writing a
 * small module instead reaches every command the same way.
 *
 * Env files are checked `.env.local` first, then `.env`, and a variable already set is never
 * overwritten — so a real shell variable beats both files, and `.env.local` beats `.env`.
 *
 *     node scripts/with-env.mjs serve
 */

import { spawnSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { loadEnvFiles } from './load-env-files.mjs'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const GENERATED = resolve(ROOT, 'src/app/infrastructure/http/env.generated.ts')

/** Checked in this order; the first file to define a variable wins. */
const ENV_FILES = ['.env.local', '.env']

/** Variables every command needs, with what to say when one is missing. */
const REQUIRED = {
  NG_APP_API_URL: 'base URL of the Bitrate API, e.g. http://localhost:3000',
}

/** Variables only `serve` needs; other commands never read them. */
const SERVE_ONLY = {
  ADMIN_PORT: 'port the dev server listens on, e.g. 3005',
}

/** Reads and validates the environment, or explains exactly what is missing and stops. */
function readEnv(needsServeVars) {
  const wanted = needsServeVars ? { ...REQUIRED, ...SERVE_ONLY } : REQUIRED
  const missing = Object.entries(wanted).filter(([name]) => !process.env[name]?.trim())

  if (missing.length > 0) {
    console.error('Cannot configure the operator panel:')
    for (const [name, hint] of missing) console.error(`  - ${name} is not set — ${hint}`)
    console.error('\nSet them in apps/admin/.env — see apps/admin/.env.example.')
    process.exit(1)
  }

  return Object.fromEntries(Object.keys(wanted).map((name) => [name, process.env[name].trim()]))
}

/** Writes the module the application imports, leaving it untouched when nothing changed. */
function writeGenerated(env) {
  const body = `/**
 * Generated by scripts/with-env.mjs from the environment — do not edit, and do not commit.
 * Regenerated by every \`pnpm --filter @bitrate/admin <script>\` that needs it.
 */
export const ENV = {
  /** Base URL of the Bitrate API, from NG_APP_API_URL. */
  apiUrl: ${JSON.stringify(env.NG_APP_API_URL)},
} as const
`

  mkdirSync(dirname(GENERATED), { recursive: true })

  const current = (() => {
    try {
      return readFileSync(GENERATED, 'utf8')
    } catch {
      return null
    }
  })()

  if (current !== body) writeFileSync(GENERATED, body)
}

const args = process.argv.slice(2)
const generateOnly = args[0] === '--generate-only'
loadEnvFiles({ root: ROOT, files: ENV_FILES })
const env = readEnv(args[0] === 'serve')

writeGenerated(env)

if (generateOnly) process.exit(0)

const ngArgs = args[0] === 'serve' ? [...args, '--port', env.ADMIN_PORT] : args
const ng = spawnSync('ng', ngArgs, { cwd: ROOT, stdio: 'inherit', shell: true })

process.exit(ng.status ?? 1)
